/* ============================================================
   SAMPLE DATA — mirrors the 17-column "QA Error Tracker" sheet.
   Columns: S NO, Month, Received Date, Client, Project, Project ID,
   Requestor, QA Resource, Production Resource, Email subject line,
   Type of QA, QA Delivery date, Error description, Comments,
   Number of Rounds, Number of issues, Bug Report.
   Replace with live sheet data in the Apps Script build.
   ============================================================ */
window.BUG_DATA = [
  {sno:85,month:"March",receivedDate:"25-Mar-2026",client:"Humana",project:"Finalization",projectId:"2798701",requestor:"Annie Newport",qaResource:"Tamizharasi",productionResource:"Daniel Savariyar / Karthi Murugesan",emailSubject:"Re: Comment on 2798701_MCD_OHHMX2QEN T3 - Versioning-Redetermination (ref# 2802157)",typeOfQA:"Finalization testing",qaDeliveryDate:"Mar 25, 2026, 6:10 PM",errorDescription:"Versioning redetermination labels mismatched on T3 layout.",comments:"Shared the report to developer in mail, verified the fixed bugs and completed.",rounds:2,issues:4,bugReport:{text:"ref# 2802157 - QA Edits",url:"https://docs.google.com/presentation/d/EXAMPLE2802157/edit"}},
  {sno:86,month:"March",receivedDate:"26-Mar-2026",client:"Nasdaq",project:"NA",projectId:"NA",requestor:"NA",qaResource:"Tamizharasi",productionResource:"Reshma V Reghu",emailSubject:"Re: [Nasdaq]: CTVAD Document Update",typeOfQA:"Content testing",qaDeliveryDate:"Mar 26, 2026, 4:20 PM",errorDescription:"Document version label and footer date outdated.",comments:"Shared the report to developer in mail, verified the fixed bugs and completed.",rounds:1,issues:3,bugReport:{text:"Nasdaq CTVAD - QA Edits",url:"https://docs.google.com/presentation/d/EXAMPLENASDAQ/edit"}},
  {sno:87,month:"March",receivedDate:"27-Mar-2026",client:"GasEntec",project:"Lp",projectId:"",requestor:"",qaResource:"Sowmiya Chandran",productionResource:"Ganesh Bista",emailSubject:"GasEntec QA Request",typeOfQA:"Landing page Testing",qaDeliveryDate:"Mar 27, 2026, 5:45 PM",errorDescription:"CTA button alignment broken below 768px; hero text overflow.",comments:"Documented the issues and emailed the developer. Re-tested and verified the fixed edits.",rounds:2,issues:5,bugReport:{text:"GasEntec LP - QA Edits",url:"https://docs.google.com/presentation/d/EXAMPLEGAS/edit"}},
  {sno:88,month:"March",receivedDate:"2-Mar-2026",client:"Worldpay",project:"Emailer",projectId:"NA",requestor:"Lizabeth",qaResource:"Yogesh Kumar D",productionResource:"Ravikumar Velayudham",emailSubject:"Re: [EXTERNAL] Worldpay Dashboard Request",typeOfQA:"Email testing",qaDeliveryDate:"Mar 2, 2026, 3:00 PM",errorDescription:"Dark-mode rendering issue in Outlook; broken tracking link.",comments:"Shared the report to developer in mail, verified the fixed bugs and completed.",rounds:1,issues:2,bugReport:{text:"Worldpay Emailer - QA Edits",url:"https://docs.google.com/presentation/d/EXAMPLEWP/edit"}},
  {sno:89,month:"March",receivedDate:"10-Mar-2026",client:"Fiserv",project:"--",projectId:"NA",requestor:"NA",qaResource:"Yogesh Kumar D",productionResource:"Surendiran Raja",emailSubject:"HRA/Reject/Rule/MPOS - Investigation Tab",typeOfQA:"Functionality Testing",qaDeliveryDate:"Mar 10, 2026, 7:15 PM",errorDescription:"Reject rule tab not loading MPOS investigation results.",comments:"Documented the issues and emailed the developer. Re-tested and verified.",rounds:3,issues:8,bugReport:{text:"Fiserv MPOS - QA Edits",url:"https://docs.google.com/presentation/d/EXAMPLEFISERV/edit"}},
  {sno:90,month:"March",receivedDate:"19-Mar-2026",client:"Humana",project:"Finalization",projectId:"2110214",requestor:"Paige Shannon",qaResource:"Yogesh Kumar D",productionResource:"Venkata Priya",emailSubject:"Re: Comment on 2110214_Go365_2025_MCD_Reward_Updates_Wellness-Visit (ref# 2110214)",typeOfQA:"Finalization testing",qaDeliveryDate:"Mar 19, 2026, 5:03 PM",errorDescription:"Please refer bug report",comments:"Shared the report to developer in mail, verified the fixed bugs and completed.",rounds:2,issues:6,bugReport:{text:"ref# 2110214 - QA Edits",url:"https://docs.google.com/presentation/d/EXAMPLE2110214/edit"}},
  {sno:91,month:"March",receivedDate:"30-Mar-2026",client:"Humana",project:"Microsites",projectId:"NA",requestor:"Courtney Smith",qaResource:"Yogesh Kumar D",productionResource:"Karthi Murugesan",emailSubject:"Re: March 2026 Humana Website Uploads - New Articles & Removals",typeOfQA:"Microsite testing",qaDeliveryDate:"Mar 31, 2026, 7:00 PM",errorDescription:"Please refer bug report",comments:"Shared the report to developer in mail, verified the fixed bugs and completed.",rounds:3,issues:29,bugReport:{text:"Humana Website Uploads - QA Edits",url:"https://docs.google.com/presentation/d/EXAMPLEHUMANA/edit"}},
  {sno:92,month:"April",receivedDate:"2-Apr-2026",client:"Global Payments",project:"Landing Page",projectId:"NA",requestor:"Mike C Pisani",qaResource:"Tamizharasi",productionResource:"Sivakarthik Gnanapandithan",emailSubject:"Re: GP: Genius Spanish Landing Page",typeOfQA:"Landing page Testing, Content testing, Browser stack testing, Functionality Testing",qaDeliveryDate:"Apr 3, 2026, 4:46 PM",errorDescription:"If the input is any random 5 digit number the zip code text displays in English instead of Spanish.",comments:"1. Tested full content QA, design, style & functionality. 2. Documented issues & emailed developer. 3. Re-tested & verified fixed edits. 4. Sent final email to proceed.",rounds:2,issues:7,bugReport:{text:"GP Spanish LP - QA Edits",url:"https://docs.google.com/presentation/d/1wPLAi6qlcWXiiIPrkl2QdXJVDEuBoAetm/edit"}},
  {sno:93,month:"April",receivedDate:"6-Apr-2026",client:"GasEntec",project:"Infographics",projectId:"NA",requestor:"Daniel R",qaResource:"Sowmiya Chandran",productionResource:"Ganesh Bista",emailSubject:"Re: GasEntec Infographic Set 2",typeOfQA:"Content testing, PDF testing, Infographics testing",qaDeliveryDate:"Thu, Apr 9, 2026, 6:44 PM",errorDescription:"Link missing, text spell check, font style issues.",comments:"1. Tested full content QA, design & style. 2. Documented issues & emailed developer. 3. Re-tested & verified. 4. Sent final email to proceed.",rounds:2,issues:4,bugReport:{text:"GasEntec Infographics - QA Edits",url:"https://docs.google.com/presentation/d/1g1Dw3M_prnb8Fd3ErLv2EVKcjWomHXZ/edit"}},
  {sno:94,month:"April",receivedDate:"8-Apr-2026",client:"Humana",project:"Finalization",projectId:"2799120",requestor:"Annie Newport",qaResource:"Praveen Kumar S",productionResource:"Venkata Priya",emailSubject:"Re: Figma comment 2799120 MCD plan compare",typeOfQA:"Figma testing",qaDeliveryDate:"Apr 9, 2026, 4:47 PM",errorDescription:"Client comment missing on the compare-plans module.",comments:"Shared the report to developer in mail, verified the fixed bugs and completed.",rounds:1,issues:2,bugReport:{text:"Figma 2799120 - QA Edits",url:"https://docs.google.com/presentation/d/1AvfmsSGpw56dnwaLOrLWOFBm9KTz1N/edit"}},
  {sno:95,month:"April",receivedDate:"13-Apr-2026",client:"Worldpay",project:"Microsites",projectId:"NA",requestor:"Lizabeth",qaResource:"Praveen Kumar S",productionResource:"Ravikumar Velayudham",emailSubject:"Re: Worldpay Client Edits Round 2",typeOfQA:"Client edits",qaDeliveryDate:"Wed, Apr 15, 2026, 2:44 PM",errorDescription:"Link not redirected to the correct destination page.",comments:"Shared the report to developer in mail, verified the fixed bugs and completed.",rounds:1,issues:2,bugReport:{text:"Worldpay Client Edits - QA Edits",url:"https://docs.google.com/presentation/d/1BRUIhubPNFfD3BkICAXzAGvUmIF9/edit"}},
  {sno:96,month:"April",receivedDate:"19-Apr-2026",client:"Humana",project:"Finalization",projectId:"2810044",requestor:"Paige Shannon",qaResource:"Divya Ramesh",productionResource:"Karthi Murugesan",emailSubject:"Re: Finalization LOB update 2810044",typeOfQA:"Finalization",qaDeliveryDate:"Tue, Apr 21, 2026, 1:54 AM",errorDescription:"Update correct LOB on the redetermination notice.",comments:"Shared the report to developer in mail, verified the fixed bugs and completed.",rounds:1,issues:1,bugReport:{text:"LOB 2810044 - QA Edits",url:"https://docs.google.com/presentation/d/1BRUIhubPNFfD3BkICAXzAGvUmIF9/edit"}},
  {sno:97,month:"April",receivedDate:"14-Apr-2026",client:"Nasdaq",project:"Translation",projectId:"NA",requestor:"Erik Lund",qaResource:"Divya Ramesh",productionResource:"Reshma V Reghu",emailSubject:"Re: [Nasdaq] CTVAD Translation FR/DE",typeOfQA:"Translation testing",qaDeliveryDate:"Apr 16, 2026, 2:47 PM",errorDescription:"The file name, content, DIN number and address related issues.",comments:"1. Tested full content QA & links for translation request. 2. Documented issues & emailed developer. 3. Re-tested & verified. 4. Sent final email.",rounds:2,issues:7,bugReport:{text:"Nasdaq Translation - QA Edits",url:"https://docs.google.com/presentation/d/1cT0Z1l6F1hxqcX0oI_uGdVEMaqDF-2T32/edit"}},
  {sno:98,month:"April",receivedDate:"15-Apr-2026",client:"GasEntec",project:"Article Pages",projectId:"NA",requestor:"Daniel R",qaResource:"Sowmiya Chandran",productionResource:"Ganesh Bista",emailSubject:"Re: GasEntec Media Article Pages",typeOfQA:"Article pages testing, Content testing",qaDeliveryDate:"Apr 16, 2026, 9:04 PM",errorDescription:"In Media article page the date format displays as mm/dd/yy but in the appointments page it is dd/mm/yy — two different date formats.",comments:"DEV Comment: Thanks for the findings. We are ignoring this since it's already approved.",rounds:"NA",issues:1,bugReport:{text:"NA",url:""}},
  {sno:99,month:"April",receivedDate:"17-Apr-2026",client:"Humana",project:"Microsites",projectId:"OKHMX4VEN",requestor:"Courtney Smith",qaResource:"Tamizharasi",productionResource:"Karthi Murugesan",emailSubject:"Re: Humana Footer Figma Design Check",typeOfQA:"Client's comment testing, Figma design testing",qaDeliveryDate:"Mon, Apr 20, 2026, 10:13 PM",errorDescription:"The file id number OKHMX4VEN was not available in the desktop footer.",comments:"1. Tested full content QA & client comments vs Figma design. 2. Sent issues with screenshot & emailed developer. 3. Re-tested & verified. 4. Sent final email.",rounds:2,issues:1,bugReport:{text:"NA",url:""}},
  {sno:100,month:"April",receivedDate:"21-Apr-2026",client:"Fiserv",project:"Dashboard",projectId:"NA",requestor:"Megan F",qaResource:"Yogesh Kumar D",productionResource:"Surendiran Raja",emailSubject:"Re: Fiserv Full QA - Reporting Module",typeOfQA:"Full QA, Content QA with PDF, ADA testing, Cross browser",qaDeliveryDate:"Apr 23, 2026, 6:30 PM",errorDescription:"ADA contrast failures on table headers; PDF export missing summary row.",comments:"Documented issues with ADA report & emailed developer. Re-tested & verified fixed edits.",rounds:2,issues:9,bugReport:{text:"Fiserv Reporting - QA Edits",url:"https://docs.google.com/presentation/d/EXAMPLEFISERV2/edit"}},
  {sno:101,month:"April",receivedDate:"24-Apr-2026",client:"Global Payments",project:"Emailer",projectId:"NA",requestor:"Mike C Pisani",qaResource:"Praveen Kumar S",productionResource:"Sivakarthik Gnanapandithan",emailSubject:"Re: GP Promo Emailer May Wave",typeOfQA:"Email testing, Content testing",qaDeliveryDate:"Apr 25, 2026, 12:20 PM",errorDescription:"Footer unsubscribe link wrong; preheader text duplicated.",comments:"Shared the report to developer in mail, verified the fixed bugs and completed.",rounds:1,issues:3,bugReport:{text:"GP Emailer - QA Edits",url:"https://docs.google.com/presentation/d/EXAMPLEGP2/edit"}},
  {sno:102,month:"April",receivedDate:"27-Apr-2026",client:"Nasdaq",project:"Landing Page",projectId:"NA",requestor:"Erik Lund",qaResource:"Divya Ramesh",productionResource:"Reshma V Reghu",emailSubject:"Re: Nasdaq IR Landing Page Refresh",typeOfQA:"Landing page Testing, Browser stack testing",qaDeliveryDate:"Apr 29, 2026, 3:40 PM",errorDescription:"Chart tooltip overlaps legend on Safari; mobile nav not collapsing.",comments:"Documented browser issues & emailed developer. Re-tested & verified.",rounds:2,issues:6,bugReport:{text:"Nasdaq IR LP - QA Edits",url:"https://docs.google.com/presentation/d/EXAMPLENASDAQ2/edit"}},
  {sno:103,month:"May",receivedDate:"4-May-2026",client:"Humana",project:"Finalization",projectId:"2815509",requestor:"Annie Newport",qaResource:"Tamizharasi",productionResource:"Venkata Priya",emailSubject:"Re: Comment on 2815509 MCD Benefits Summary",typeOfQA:"Finalization testing, Content testing",qaDeliveryDate:"May 5, 2026, 5:15 PM",errorDescription:"Benefit amount mismatch vs source; superscript footnote missing.",comments:"Shared the report to developer in mail, verified the fixed bugs and completed.",rounds:2,issues:5,bugReport:{text:"ref# 2815509 - QA Edits",url:"https://docs.google.com/presentation/d/EXAMPLE2815509/edit"}},
  {sno:104,month:"May",receivedDate:"6-May-2026",client:"Worldpay",project:"Landing Page",projectId:"NA",requestor:"Lizabeth",qaResource:"Yogesh Kumar D",productionResource:"Ravikumar Velayudham",emailSubject:"Re: Worldpay Merchant LP - QA",typeOfQA:"Landing page Testing, Functionality Testing",qaDeliveryDate:"May 7, 2026, 4:05 PM",errorDescription:"Form validation accepts invalid email; CTA scroll anchor broken.",comments:"Documented issues & emailed developer. Re-tested & verified fixed edits.",rounds:2,issues:4,bugReport:{text:"Worldpay Merchant LP - QA Edits",url:"https://docs.google.com/presentation/d/EXAMPLEWP2/edit"}},
  {sno:105,month:"May",receivedDate:"8-May-2026",client:"GasEntec",project:"Lp",projectId:"NA",requestor:"Daniel R",qaResource:"Sowmiya Chandran",productionResource:"Ganesh Bista",emailSubject:"Re: GasEntec Product LP Round 3",typeOfQA:"Content testing, Functionality Testing",qaDeliveryDate:"May 9, 2026, 1:30 PM",errorDescription:"Spec table values inconsistent with PDF datasheet.",comments:"Shared the report to developer in mail, verified the fixed bugs and completed.",rounds:3,issues:6,bugReport:{text:"GasEntec Product LP - QA Edits",url:"https://docs.google.com/presentation/d/EXAMPLEGAS2/edit"}},
  {sno:106,month:"May",receivedDate:"11-May-2026",client:"Humana",project:"Microsites",projectId:"NA",requestor:"Courtney Smith",qaResource:"Praveen Kumar S",productionResource:"Karthi Murugesan",emailSubject:"Re: May 2026 Humana Article Uploads",typeOfQA:"Microsite testing, Content testing",qaDeliveryDate:"May 12, 2026, 6:50 PM",errorDescription:"Three article URLs return 404; breadcrumb label typo.",comments:"Documented issues & emailed developer. Re-tested & verified fixed edits.",rounds:2,issues:11,bugReport:{text:"Humana May Uploads - QA Edits",url:"https://docs.google.com/presentation/d/EXAMPLEHUMANA2/edit"}},
  {sno:107,month:"May",receivedDate:"13-May-2026",client:"Fiserv",project:"Emailer",projectId:"NA",requestor:"Megan F",qaResource:"Divya Ramesh",productionResource:"Surendiran Raja",emailSubject:"Re: Fiserv Onboarding Email Series",typeOfQA:"Email testing",qaDeliveryDate:"May 14, 2026, 11:10 AM",errorDescription:"Merge tag fallback missing; image alt text empty.",comments:"Shared the report to developer in mail, verified the fixed bugs and completed.",rounds:1,issues:3,bugReport:{text:"Fiserv Onboarding - QA Edits",url:"https://docs.google.com/presentation/d/EXAMPLEFISERV3/edit"}},
  {sno:108,month:"May",receivedDate:"18-May-2026",client:"Global Payments",project:"Microsites",projectId:"NA",requestor:"Mike C Pisani",qaResource:"Tamizharasi",productionResource:"Sivakarthik Gnanapandithan",emailSubject:"Re: GP Partner Portal Content",typeOfQA:"Content testing, ADA testing",qaDeliveryDate:"May 19, 2026, 4:25 PM",errorDescription:"ADA focus order incorrect; heading hierarchy skips H2.",comments:"Documented ADA issues & emailed developer. Re-tested & verified.",rounds:2,issues:5,bugReport:{text:"GP Partner Portal - QA Edits",url:"https://docs.google.com/presentation/d/EXAMPLEGP3/edit"}},
  {sno:109,month:"May",receivedDate:"20-May-2026",client:"Nasdaq",project:"NA",projectId:"NA",requestor:"Erik Lund",qaResource:"Yogesh Kumar D",productionResource:"Reshma V Reghu",emailSubject:"Re: [Nasdaq] Annual Report PDF Proof",typeOfQA:"PDF testing, Content testing",qaDeliveryDate:"May 21, 2026, 2:00 PM",errorDescription:"PDF bookmarks missing; page numbers off by one in TOC.",comments:"Documented issues & emailed developer. Re-tested & verified fixed edits.",rounds:2,issues:8,bugReport:{text:"Nasdaq Annual Report - QA Edits",url:"https://docs.google.com/presentation/d/EXAMPLENASDAQ3/edit"}},
  {sno:110,month:"May",receivedDate:"22-May-2026",client:"Humana",project:"Finalization",projectId:"2820731",requestor:"Paige Shannon",qaResource:"Sowmiya Chandran",productionResource:"Venkata Priya",emailSubject:"Re: Comment on 2820731 MCD Drug List",typeOfQA:"Finalization testing",qaDeliveryDate:"May 23, 2026, 5:40 PM",errorDescription:"Drug tier column misaligned; legend color swatch wrong.",comments:"Shared the report to developer in mail, verified the fixed bugs and completed.",rounds:2,issues:4,bugReport:{text:"ref# 2820731 - QA Edits",url:"https://docs.google.com/presentation/d/EXAMPLE2820731/edit"}},
  {sno:111,month:"May",receivedDate:"26-May-2026",client:"Worldpay",project:"Emailer",projectId:"NA",requestor:"Lizabeth",qaResource:"Praveen Kumar S",productionResource:"Ravikumar Velayudham",emailSubject:"Re: Worldpay Statement Email QA",typeOfQA:"Email testing, Cross browser",qaDeliveryDate:"May 27, 2026, 10:50 AM",errorDescription:"Button not clickable in Gmail app; dynamic year shows 2025.",comments:"Documented issues & emailed developer. Re-tested & verified fixed edits.",rounds:1,issues:2,bugReport:{text:"Worldpay Statement - QA Edits",url:"https://docs.google.com/presentation/d/EXAMPLEWP3/edit"}},
  {sno:112,month:"May",receivedDate:"28-May-2026",client:"GasEntec",project:"Landing Page",projectId:"NA",requestor:"Daniel R",qaResource:"Divya Ramesh",productionResource:"Ganesh Bista",emailSubject:"Re: GasEntec Campaign LP Final",typeOfQA:"Landing page Testing, Browser stack testing, ADA testing",qaDeliveryDate:"May 29, 2026, 3:15 PM",errorDescription:"Hero video autoplay blocked on iOS; missing skip-to-content link.",comments:"Documented issues & emailed developer. Re-tested & verified fixed edits.",rounds:2,issues:6,bugReport:{text:"GasEntec Campaign LP - QA Edits",url:"https://docs.google.com/presentation/d/EXAMPLEGAS3/edit"}}
];
